apiVersion: apps/v1
kind: Deployment
metadata:
  name: neko
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neko
  template:
    metadata:
      labels:
        app: neko
    spec:
      containers:
      - name: neko
        image: m1k1o/neko:firefox
        ports:
        - containerPort: 8080
        - containerPort: 52000-52100
        env:
        - name: NEKO_SCREEN
          value: "1920x1080@30"
        - name: NEKO_PASSWORD
          value: neko
        - name: NEKO_PASSWORD_ADMIN
          value: admin
        - name: NEKO_EPR
          value: 52000-52100
        - name: NEKO_ICELITE
          value: "1"
      shmSize: "2G"

