kind: Service
metadata:
  name: neko
spec:
  type: LoadBalancer
  selector:
    app: neko
  ports:
  - name: tcp-port
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: udp-port
    protocol: UDP
    port: 52000
    targetPort: 52000
