apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: 
spec:
  containers:
  - name: dnsutils
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command: ["/bin/sh", "-c", "sleep 3600"]
