apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  namespace:
spec:
  containers:
  - name: ubuntu-container
    image: pgnomme/ubuntu-to-go:22.04
    command: [ "bash", "-c", "while true; do sleep 3600; done" ]
    tty: true
    stdin: true

