---
###################################################
# Persistence Volume Claim
###################################################
kind: PersistentVolume
apiVersion: v1
metadata:
  name: git-pv
  namespace: gitea-git
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: gitea-git
    name: git-pvc
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: git-data
  storageClassName: longhorn-durable
  ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-pvc
  namespace: gitea-git
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-durable
  resources:
    requests:
      storage: 5Gi
  volumeName: "git-pv"
