apiVersion: v1
kind: PersistentVolume
metadata:
  name: firefox-claim0
  labels:
    io.kompose.service: firefox-claim0
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: /data/firefox/
